version: "3"
networks:
  server:
services:
  indexify:
    image: tensorlake/indexify-server
    ports:
      - 8900:8900
    networks:
      server:
        aliases:
          - indexify-server
    volumes:
      - data:/tmp/indexify-blob-storage
  download-executor:
    image: tensorlake/pdf-blueprint-download:latest
    command:
      [
        "indexify-cli",
        "executor",
        "--server-addr",
        "indexify:8900"
      ]
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
    deploy:
      mode: replicated
      replicas: 1
  embedding-executor:
    image: tensorlake/pdf-blueprint-st
    command:
      [
        "indexify-cli",
        "executor",
        "--server-addr",
        "indexify:8900"
      ]
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
    deploy:
      mode: replicated
      replicas: 1
  chromadb-executor:
    image: tensorlake/blueprints-chromadb
    command:
      [
        "indexify-cli",
        "executor",
        "--server-addr",
        "indexify:8900"
      ]
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
  pdf-parser-executor:
    # Use this for GPU support
    image: tensorlake/pdf-blueprint-pdf-parser-gpu:latest
    #image: tensorlake/pdf-blueprint-pdf-parser:latest
    command:
      [
        "indexify-cli",
        "executor",
        "--server-addr",
        "indexify:8900"
      ]
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
    deploy:
      mode: replicated
      replicas: 1
      # Uncomment this for GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  chromadb:
    image: chromadb/chroma
    networks:
      server:
    volumes:
      - data:/tmp/indexify-blob-storage
    ports:
      - 8000:8000


volumes:
  data:
